"""Shared eiprotocol v0.1 MVP contracts for EI projects.

This module is the canonical public contract surface for EI events.
Callers should import through this package instead of directly importing
individual internal builder/helper modules whenever possible.
"""

from .builders import (
    EventIdFactory,
    EventIds,
    build_action_request_event,
    build_asr_event,
    build_dialogue_cancellation_applied_event,
    build_dialogue_fast_hypothesis_event,
    build_dialogue_stable_decision_event,
    build_emotion_context_event,
    build_event,
    build_execution_outcome_event,
    build_head_status_report_event,
    build_memory_policy_report_event,
    build_memory_prefetch_requested_event,
    build_proactive_activity_proposed_event,
    build_speech_action_plan_event,
    build_voice_asr_event,
    build_voice_audio_frame_event,
    build_voice_barge_in_detected_event,
    build_voice_playback_state_event,
    build_voice_session_heartbeat_event,
    build_voice_tts_chunk_event,
    build_voice_tts_sentence_start_event,
    build_vision_event_event,
    build_vision_frame_event,
    build_vision_scene_event,
)
from .catalog import (
    EventDefinition,
    get_event_definition,
    is_known_event,
    list_event_names,
    require_event_definition,
)
from .codec import (
    EventDecodeError,
    canonical_event_json,
    dumps_event,
    event_to_dict,
    loads_event,
)
from .event_routing import classify_event
from .models import (
    SPEC_VERSION,
    AudioTurn,
    Capability,
    CapabilityManifest,
    Detection,
    DeviceStatus,
    DialogueCancellationApplied,
    DialogueFastHypothesis,
    DialogueStableDecision,
    EmotionContext,
    EventEnvelope,
    ExecutionOutcome,
    HeadAction,
    HeadStatusReport,
    MemoryPolicyReport,
    MemoryPrefetchRequest,
    PolicyState,
    ProactiveActivityProposal,
    RealtimeVisionObservation,
    SourceRef,
    SpeechActionPlan,
    TargetRef,
    UserFeedback,
    VisionEventObservation,
    VisionSceneObservation,
    validate_event,
)
from .validation import ValidationIssue, assert_event_valid, validate_event_strict

__all__ = [
    "SPEC_VERSION",
    "AudioTurn",
    "Capability",
    "CapabilityManifest",
    "Detection",
    "DeviceStatus",
    "DialogueCancellationApplied",
    "DialogueFastHypothesis",
    "DialogueStableDecision",
    "EmotionContext",
    "EventEnvelope",
    "ExecutionOutcome",
    "HeadAction",
    "HeadStatusReport",
    "MemoryPolicyReport",
    "MemoryPrefetchRequest",
    "PolicyState",
    "ProactiveActivityProposal",
    "RealtimeVisionObservation",
    "SourceRef",
    "SpeechActionPlan",
    "TargetRef",
    "UserFeedback",
    "VisionEventObservation",
    "VisionSceneObservation",
    "EventDefinition",
    "EventDecodeError",
    "EventIdFactory",
    "EventIds",
    "ValidationIssue",
    "assert_event_valid",
    "build_action_request_event",
    "build_asr_event",
    "build_dialogue_cancellation_applied_event",
    "build_dialogue_fast_hypothesis_event",
    "build_dialogue_stable_decision_event",
    "build_emotion_context_event",
    "build_event",
    "build_execution_outcome_event",
    "build_head_status_report_event",
    "build_memory_policy_report_event",
    "build_memory_prefetch_requested_event",
    "build_proactive_activity_proposed_event",
    "build_speech_action_plan_event",
    "build_voice_asr_event",
    "build_voice_audio_frame_event",
    "build_voice_barge_in_detected_event",
    "build_voice_playback_state_event",
    "build_voice_session_heartbeat_event",
    "build_voice_tts_chunk_event",
    "build_voice_tts_sentence_start_event",
    "build_vision_event_event",
    "build_vision_frame_event",
    "build_vision_scene_event",
    "canonical_event_json",
    "classify_event",
    "dumps_event",
    "event_to_dict",
    "get_event_definition",
    "is_known_event",
    "list_event_names",
    "loads_event",
    "require_event_definition",
    "validate_event",
    "validate_event_strict",
]
